root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/main"
cmd = "task livereload"
# delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_file = []
exclude_regex = ["_test.go", ".*_templ.go"]
include_dir = []
include_ext = ["go", "tpl", "tmpl", "templ", "html"]

[misc]
clean_on_exit = true
